// Feed, sitemap, web app manifest and service worker: the files a server used
// to generate on the fly, now written once per build.
import { escapeHTML as x } from './markdown.mjs';
import { postPath } from '../../src/render.js';

// Atom, ordered like the home page (pinned first, then newest first). The
// profile README's "latest posts" sync reads the first entries in this order.
export function atomFeed(site, posts, now) {
  const host = site.config.host;
  const ordered = [...posts.filter(p => p.pinned), ...posts.filter(p => !p.pinned)];
  const updated = ordered.reduce((m, p) => (p.updated && p.updated > m ? p.updated : m), ordered[0]?.updated || now.toISOString());
  return `<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xml:lang="zh-CN">
  <title>${x(site.config.name)}</title>
  <subtitle>${x(site.config.description)}</subtitle>
  <id>${x(host)}/</id>
  <link href="${x(host)}/"/>
  <link rel="self" type="application/atom+xml" href="${x(host)}/feed.xml"/>
  <updated>${x(updated)}</updated>
  <author><name>${x(site.config.author)}</name>${site.config.email ? `<email>${x(site.config.email)}</email>` : ''}</author>
  <icon>${x(host)}/favicon.ico</icon>
${ordered.map(p => {
    const url = host + postPath(p);
    return `  <entry>
    <title>${x(p.title)}</title>
    <link href="${x(url)}"/>
    <id>${x(url)}</id>
    <published>${x(p.created)}</published>
    <updated>${x(p.updated || p.created)}</updated>
${p.category ? `    <category term="${x(p.category.name)}"/>\n` : ''}${p.tags.map(t => `    <category term="${x(t.name)}"/>\n`).join('')}    <summary>${x(p.description)}</summary>
    <content type="html">${x(p.html)}</content>
  </entry>`;
  }).join('\n')}
</feed>
`;
}

export function sitemap(site, now) {
  const host = site.config.host;
  const day = iso => (iso || now.toISOString()).slice(0, 10);
  const latest = site.posts.reduce((m, p) => (p.updated > m ? p.updated : m), '');
  const urls = [
    [`${host}/`, day(latest), '1.0'],
    ...site.posts.map(p => [host + postPath(p), day(p.updated), '0.8']),
    ...site.pages.map(p => [`${host}/pages/${encodeURI(p.id)}`, day(latest), '0.5']),
    ...['archive', 'tags', 'reading', 'stats'].map(s => [`${host}/${s}`, day(latest), '0.4']),
  ];
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(([loc, lastmod, priority]) => `  <url><loc>${x(loc)}</loc><lastmod>${lastmod}</lastmod><priority>${priority}</priority></url>`).join('\n')}
</urlset>
`;
}

export function manifest(site, base = '') {
  return JSON.stringify({
    name: site.config.name,
    short_name: site.config.name,
    description: site.config.description,
    lang: 'zh-CN',
    start_url: `${base}/`,
    scope: `${base}/`,
    display: 'standalone',
    background_color: '#eef0f6',
    theme_color: '#eef0f6',
    icons: [
      { src: `${base}/icons/icon-192.png`, sizes: '192x192', type: 'image/png' },
      { src: `${base}/icons/icon-512.png`, sizes: '512x512', type: 'image/png' },
      { src: `${base}/icons/icon-512.png`, sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  }, null, 2);
}

// Offline reading: pages and article data are network-first with the last
// copy as fallback, fingerprinted assets are cache-first, other files
// stale-while-revalidate. A page never visited falls back to /offline.
export function serviceWorker(version, base, precache) {
  return `// generated by scripts/build.mjs
const VERSION = ${JSON.stringify(version)};
const BASE = ${JSON.stringify(base)};
const CACHE = 'blog-' + VERSION;
const PRECACHE = ${JSON.stringify(precache)};

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k.startsWith('blog-') && k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim()));
});

async function networkFirst(req, fallback) {
  const cache = await caches.open(CACHE);
  try {
    const res = await fetch(req);
    if (res.ok) cache.put(req, res.clone());
    return res;
  } catch (err) {
    const hit = await cache.match(req, { ignoreSearch: req.mode !== 'navigate' ? false : true });
    if (hit) return hit;
    if (fallback) { const off = await cache.match(fallback); if (off) return off; }
    throw err;
  }
}
async function cacheFirst(req) {
  const hit = await caches.match(req);
  if (hit) return hit;
  const res = await fetch(req);
  if (res.ok) (await caches.open(CACHE)).put(req, res.clone());
  return res;
}
async function staleWhileRevalidate(req) {
  const cache = await caches.open(CACHE);
  const hit = await cache.match(req);
  const fresh = fetch(req).then(res => { if (res.ok) cache.put(req, res.clone()); return res; }).catch(() => hit);
  return hit || fresh;
}

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin || !url.pathname.startsWith(BASE + '/')) return;
  const path = url.pathname.slice(BASE.length);
  if (/^\\/(feed|feed\\.xml|sitemap\\.xml|robots\\.txt|intro)/.test(path)) return;
  if (req.mode === 'navigate') { e.respondWith(networkFirst(req, BASE + '/offline')); return; }
  if (path.startsWith('/assets/')) { e.respondWith(cacheFirst(req)); return; }
  if (path.startsWith('/data/')) { e.respondWith(networkFirst(req)); return; }
  e.respondWith(staleWhileRevalidate(req));
});
`;
}
